Repository woowacourse-teams/2020-devbie, pull requests merged in 2020-09, with the labels that each got.

#232 feat: 질문 도메인 반응형(responsive) css 적용
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/App.vue
  src/frontend/src/components/NavagationBar.vue
  src/frontend/src/components/SnackBar.vue
  src/frontend/src/components/chat/ChatDrawer.vue
  src/frontend/src/components/chat/chatInfo.vue
  src/frontend/src/components/hashtag/HashtagList.vue
  src/frontend/src/components/question/AnswerCreate.vue
  src/frontend/src/components/question/AnswerItem.vue
  src/frontend/src/components/question/AnswerList.vue
  src/frontend/src/components/question/FormButton.vue
  src/frontend/src/components/question/QuestionControl.vue
  src/frontend/src/components/question/QuestionDetail.vue
  src/frontend/src/components/question/QuestionDetailMenu.vue
  src/frontend/src/components/question/QuestionFilters.vue
  src/frontend/src/components/question/QuestionForm.vue
  src/frontend/src/components/question/QuestionList.vue
  src/frontend/src/components/question/RecommendationControl.vue
  src/frontend/src/components/question/SearchBar.vue
  src/frontend/src/css/app.css
  src/frontend/src/main.js
  src/frontend/src/views/question/QuestionDetailView.vue
  src/frontend/src/views/question/QuestionListView.vue
Labels: 🌈 View

#257 [Fix] CI과정에서 Pull Request는 배포하지 않도록 설정
  .travis.yml
Labels: ⚙️ Infra

#253 [Feature] ControllerAdvice 로깅 추가 및 필터 리팩토링
  src/main/java/underdogs/devbie/advice/ControllerAdvice.java
  src/main/java/underdogs/devbie/exception/CreateFailException.java
  src/main/java/underdogs/devbie/exception/IntervalServerException.java
  src/main/java/underdogs/devbie/exception/NotExistException.java
  src/main/java/underdogs/devbie/filter/ReadableRequestWrapperFilter.java
Labels: 🐛 Bug, 💡 Features, 📮 Server, 🛠 Refactoring

#245 refactor: 동물 이름에서 크루 닉네임으로 변경
  src/main/java/underdogs/devbie/chat/domain/Animal.java
  src/main/java/underdogs/devbie/chat/domain/ChatName.java
  src/main/java/underdogs/devbie/chat/domain/ChatNameFactory.java
  src/main/java/underdogs/devbie/chat/domain/CrewName.java
  src/test/java/underdogs/devbie/chat/controller/ChatControllerTest.java
  src/test/java/underdogs/devbie/chat/domain/ChatNameFactoryTest.java
  src/test/java/underdogs/devbie/chat/domain/ChatNameTest.java
  src/test/java/underdogs/devbie/chat/domain/ChatNamesTest.java
  src/test/java/underdogs/devbie/chat/domain/ChatRoomTest.java
  src/test/java/underdogs/devbie/chat/domain/ChatTest.java
  src/test/java/underdogs/devbie/chat/service/ChatServiceTest.java
Labels: 📮 Server, 🛠 Refactoring

#267 [Feature] 채팅방 접속 이력 보여주기
  src/frontend/src/App.vue
  src/frontend/src/components/chat/ChatDrawer.vue
  src/frontend/src/components/chat/ChatInfo.vue
  src/frontend/src/components/chat/ChatRoomDrawer.vue
  src/frontend/src/components/chat/ChatRoomHistoryBox.vue
  src/frontend/src/components/chat/ChatRoomTitleBox.vue
  src/frontend/src/components/notice/NoticeDetail.vue
  src/frontend/src/store/modules/chat.js
Labels: 🌈 View, 💡 Features

#259 refactor : 테스트 격리 및 테스트 커버리지 보완
  build.gradle
  src/main/java/underdogs/devbie/answer/domain/Answer.java
  src/main/java/underdogs/devbie/chat/domain/ChatRoom.java
  src/main/java/underdogs/devbie/exception/NotExistException.java
  src/main/java/underdogs/devbie/favorite/domain/NoticeFavorite.java
  src/main/java/underdogs/devbie/favorite/domain/QuestionFavorite.java
  src/main/java/underdogs/devbie/notice/vo/JobPositionsResponse.java
  src/main/java/underdogs/devbie/notice/vo/LanguagesResponse.java
  src/main/java/underdogs/devbie/question/domain/Hashtag.java
  src/main/java/underdogs/devbie/question/domain/Question.java
  src/main/java/underdogs/devbie/question/domain/QuestionHashtag.java
  src/main/java/underdogs/devbie/user/exception/NotMatchedUserException.java
  src/test/java/underdogs/devbie/MvcTest.java
  src/test/java/underdogs/devbie/acceptance/AcceptanceTest.java
  src/test/java/underdogs/devbie/acceptance/DatabaseCleanup.java
  src/test/java/underdogs/devbie/answer/service/AnswerServiceTest.java
  src/test/java/underdogs/devbie/chat/domain/TitleColorTest.java
  src/test/java/underdogs/devbie/notice/acceptance/NoticeAcceptanceTest.java
  src/test/java/underdogs/devbie/notice/controller/NoticeControllerTest.java
  src/test/java/underdogs/devbie/notice/domain/DurationTest.java
  src/test/java/underdogs/devbie/notice/domain/LanguageTest.java
  src/test/java/underdogs/devbie/notice/domain/NoticeDescriptionTest.java
  src/test/java/underdogs/devbie/notice/domain/NoticeTest.java
  src/test/java/underdogs/devbie/notice/service/NoticeServiceTest.java
  src/test/java/underdogs/devbie/question/service/HashtagServiceTest.java
  src/test/java/underdogs/devbie/question/service/QuestionServiceTest.java
  src/test/java/underdogs/devbie/user/controller/UserControllerTest.java
  src/test/java/underdogs/devbie/user/service/UserServiceTest.java
  src/test/resources/devbie.png
Labels: 🧪 Test

#274 Refactor hashtag 레파지토리 querydsl로 변경
  src/frontend/src/components/question/QuestionList.vue
  src/main/java/underdogs/devbie/question/domain/HashtagRepository.java
  src/main/java/underdogs/devbie/question/domain/QuestionHashtagRepository.java
  src/main/java/underdogs/devbie/question/domain/repository/HashtagRepository.java
  src/main/java/underdogs/devbie/question/domain/repository/QuestionHashtagRepository.java
  src/main/java/underdogs/devbie/question/domain/repository/QuestionHashtagRepositoryCustom.java
  src/main/java/underdogs/devbie/question/domain/repository/QuestionHashtagRepositoryImpl.java
  src/main/java/underdogs/devbie/question/domain/repository/QuestionRepository.java
  src/main/java/underdogs/devbie/question/domain/repository/QuestionRepositoryCustom.java
  src/main/java/underdogs/devbie/question/domain/repository/QuestionRepositoryImpl.java
  src/main/java/underdogs/devbie/question/service/HashtagService.java
  src/main/java/underdogs/devbie/question/service/QuestionHashtagService.java
  src/main/java/underdogs/devbie/question/service/QuestionService.java
  src/test/java/underdogs/devbie/question/domain/repository/QuestionHashtagRepositoryImplTest.java
  src/test/java/underdogs/devbie/question/service/HashtagServiceTest.java
  src/test/java/underdogs/devbie/question/service/QuestionHashtagServiceTest.java
  src/test/java/underdogs/devbie/question/service/QuestionServiceTest.java
Labels: 🛠 Refactoring

#281 [Feature] 채팅방 exit 버튼 추가
  src/frontend/src/components/chat/ChatInfo.vue
  src/frontend/src/store/modules/chat.js
Labels: 🌈 View, 💡 Features, 🔍 Review Required

#271 [Reafactor] 형용사 변경
  src/main/java/underdogs/devbie/chat/domain/Adjective.java
  src/test/java/underdogs/devbie/chat/domain/ChatNameFactoryTest.java
  src/test/java/underdogs/devbie/chat/domain/ChatNameTest.java
  src/test/java/underdogs/devbie/chat/domain/ChatNamesTest.java
Labels: 📮 Server, 🔍 Review Required, 🛠 Refactoring

#284 [Feature] 채팅 접속 이력 없을 시 문구 노출
  src/frontend/src/components/chat/ChatRoomHistoryBox.vue
Labels: 🌈 View, 💡 Features, 🔍 Review Required

#293 [Bugfix] 공고 수정이 안되는 이슈해결
  src/frontend/src/components/notice/NoticeDetail.vue
  src/frontend/src/utils/noticeUtil.js
Labels: 🌈 View, 🐛 Bug

#296 [Bigfuc] application.properties 수정
  src/main/resources/application.properties
Labels: ⚙️ Infra, 🐛 Bug, 📮 Server

#301 refactor: Question List mobile css 수정
  src/frontend/src/components/FooterBar.vue
  src/frontend/src/components/question/QuestionList.vue
Labels: 🌈 View

#305 fix: Querydsl을 이용하여 Orderby 수정
  src/main/java/underdogs/devbie/notice/domain/NoticeRepositoryImpl.java
Labels: 📮 Server

#308 docs: README 파일 작성
  README.md
Labels: 📚 Docs
