Repository woowacourse-teams/2020-devbie, pull requests merged in 2020-07, with the labels that each got.

#22 fix: Issue, PR 템플릿 수정
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🐛 Bug, 📚 Docs

#24 docs: Epic 템플릿 생성
  .github/ISSUE_TEMPLATE/epic_template.md
Labels: 📚 Docs

#28 fix: UNICODE 문자 앞에 \ 추가
  .github/ISSUE_TEMPLATE/epic_template.md
  src/frontend/package-lock.json
Labels: 🐛 Bug, 📚 Docs

#31 feat: 메인 페이지 레이아웃 구현
  src/frontend/public/index.html
  src/frontend/src/App.vue
  src/frontend/src/components/FooterBar.vue
  src/frontend/src/components/NavagationBar.vue
  src/frontend/src/main.js
  src/frontend/src/plugins/vuetify.js
Labels: 🌈 View, 💡 Features

#33 fix: Unicode 포맷을 python source로 변경
  .github/ISSUE_TEMPLATE/epic_template.md
Labels: 🐛 Bug, 📚 Docs

#37 feat: Github Oauth 로그인 구현
  .gitignore
  build.gradle
  src/frontend/package-lock.json
  src/frontend/src/App.vue
  src/frontend/src/components/LoginPage.vue
  src/frontend/src/components/NavagationBar.vue
  src/frontend/src/main.js
  src/frontend/src/router/index.js
  src/main/java/underdogs/devbie/auth/controller/AuthController.java
  src/main/java/underdogs/devbie/auth/controller/interceptor/BearerAuthInterceptor.java
  src/main/java/underdogs/devbie/auth/controller/interceptor/utils/AuthorizationExtractor.java
  src/main/java/underdogs/devbie/auth/controller/resolver/LoginUser.java
  src/main/java/underdogs/devbie/auth/controller/resolver/LoginUserArgumentResolver.java
  src/main/java/underdogs/devbie/auth/dto/AccessTokenRequest.java
  src/main/java/underdogs/devbie/auth/dto/AccessTokenResponse.java
  src/main/java/underdogs/devbie/auth/dto/JwtTokenResponse.java
  src/main/java/underdogs/devbie/auth/dto/UserInfoResponse.java
  src/main/java/underdogs/devbie/auth/dto/UserTokenDto.java
  src/main/java/underdogs/devbie/auth/exception/ExpiredTokenException.java
  src/main/java/underdogs/devbie/auth/exception/InvalidAuthenticationException.java
  src/main/java/underdogs/devbie/auth/exception/UserNotFoundException.java
  src/main/java/underdogs/devbie/auth/jwt/JwtTokenProvider.java
  src/main/java/underdogs/devbie/auth/oauth/GithubClient.java
  src/main/java/underdogs/devbie/auth/service/AuthService.java
  src/main/java/underdogs/devbie/config/AuthConfig.java
  src/main/java/underdogs/devbie/controller/HelloController.java
  src/main/java/underdogs/devbie/user/controller/UserController.java
  src/main/java/underdogs/devbie/user/domain/User.java
  src/main/java/underdogs/devbie/user/domain/UserRepository.java
  src/main/java/underdogs/devbie/user/dto/UserResponse.java
  src/main/java/underdogs/devbie/user/service/UserService.java
  src/main/resources/application.yml
Labels: 🌈 View, 💡 Features, 🔍 Review Required

#42 test: JwtTokenProvider 테스트 코드 작성
  src/main/java/underdogs/devbie/auth/exception/InvalidAuthenticationException.java
  src/test/java/underdogs/devbie/auth/jwt/JwtTokenProviderTest.java
Labels: 🧪 Test

#48 test: AuthController 테스트 코드 작성
  src/test/java/underdogs/devbie/MvcTest.java
  src/test/java/underdogs/devbie/auth/controller/AuthControllerTest.java
Labels: 🧪 Test

#26 feat: Jacoco 테스트 커버리지 설정
  build.gradle
Labels: ⚙️ Infra

#47 test: User Controller, Service, Domain 테스트 코드 작성
  src/frontend/src/components/LoginPage.vue
  src/main/java/underdogs/devbie/auth/controller/AuthController.java
  src/main/java/underdogs/devbie/auth/dto/UserInfoResponse.java
  src/main/java/underdogs/devbie/config/AuthConfig.java
  src/main/java/underdogs/devbie/user/controller/UserController.java
  src/main/java/underdogs/devbie/user/domain/User.java
  src/main/java/underdogs/devbie/user/service/UserService.java
  src/test/java/underdogs/devbie/auth/controller/AuthControllerTest.java
  src/test/java/underdogs/devbie/auth/jwt/JwtTokenProviderTest.java
  src/test/java/underdogs/devbie/user/controller/UserControllerTest.java
  src/test/java/underdogs/devbie/user/domain/UserTest.java
  src/test/java/underdogs/devbie/user/service/UserServiceTest.java
Labels: 🧪 Test

#43 refactor: 빌드환경별 application.properties 분기하도록 설정
  .gitignore
  build.gradle
Labels: ⚙️ Infra, 🛠 Refactoring

#52 fix: jacoco coverage 수정
  build.gradle
Labels: ⚙️ Infra, 🐛 Bug

#53 feat: 프론트엔드 로그인 상단 바 수정
  src/frontend/src/App.vue
  src/frontend/src/components/NavagationBar.vue
Labels: 🌈 View, 💡 Features

#36 feat: gradle.build 환경변수별 Vue build 하도록 수정
  build.gradle
Labels: ⚙️ Infra

#55 feat: BaseTimeEntity 생성
  src/main/java/underdogs/devbie/config/AuditingConfig.java
  src/main/java/underdogs/devbie/config/BaseTimeEntity.java
  src/main/java/underdogs/devbie/user/domain/User.java
Labels: 💡 Features

#61 feat: AcceptanceTest를 위한 CRUD Template 작성
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/test/java/underdogs/devbie/MvcTest.java
  src/test/java/underdogs/devbie/acceptance/AcceptanceTest.java
  src/test/java/underdogs/devbie/auth/controller/AuthControllerTest.java
  src/test/java/underdogs/devbie/user/service/UserServiceTest.java
Labels: 💡 Features, 📮 Server

#66 refactor: AcceptanceTest 수정
  src/test/java/underdogs/devbie/acceptance/AcceptanceTest.java
Labels: 💡 Features, 📮 Server, 🛠 Refactoring

#71 feat: 인수테스트에 사용할 토큰 생성 및 Interceptor 어노테이션 기반 필터링 설정
  src/main/java/underdogs/devbie/auth/controller/AuthController.java
  src/main/java/underdogs/devbie/auth/controller/interceptor/BearerAuthInterceptor.java
  src/main/java/underdogs/devbie/auth/controller/interceptor/annotation/NoValidate.java
  src/main/java/underdogs/devbie/auth/controller/interceptor/utils/InterceptorValidator.java
  src/main/java/underdogs/devbie/user/controller/UserController.java
  src/main/java/underdogs/devbie/user/dto/UserResponse.java
  src/test/java/underdogs/devbie/MvcTest.java
  src/test/java/underdogs/devbie/acceptance/AcceptanceTest.java
  src/test/java/underdogs/devbie/user/controller/UserControllerTest.java
Labels: 💡 Features, 📮 Server

#67 feat: 공고 API 구현
  build.gradle
  src/main/java/underdogs/devbie/config/AuthConfig.java
  src/main/java/underdogs/devbie/notice/controller/NoticeController.java
  src/main/java/underdogs/devbie/notice/domain/Company.java
  src/main/java/underdogs/devbie/notice/domain/Duration.java
  src/main/java/underdogs/devbie/notice/domain/JobPosition.java
  src/main/java/underdogs/devbie/notice/domain/Language.java
  src/main/java/underdogs/devbie/notice/domain/Notice.java
  src/main/java/underdogs/devbie/notice/domain/NoticeDescription.java
  src/main/java/underdogs/devbie/notice/domain/NoticeRepository.java
  src/main/java/underdogs/devbie/notice/dto/NoticeCreateRequest.java
  src/main/java/underdogs/devbie/notice/dto/NoticeDescriptionResponse.java
  src/main/java/underdogs/devbie/notice/dto/NoticeDetailResponse.java
  src/main/java/underdogs/devbie/notice/dto/NoticeResponse.java
  src/main/java/underdogs/devbie/notice/dto/NoticeResponses.java
  src/main/java/underdogs/devbie/notice/dto/NoticeUpdateRequest.java
  src/main/java/underdogs/devbie/notice/expception/CreateFailException.java
  src/main/java/underdogs/devbie/notice/expception/InvalidDurationException.java
  src/main/java/underdogs/devbie/notice/expception/NoSuchLanguageException.java
  src/main/java/underdogs/devbie/notice/expception/NoticeNotFoundException.java
  src/main/java/underdogs/devbie/notice/service/NoticeService.java
  src/test/java/underdogs/devbie/notice/acceptance/NoticeAcceptanceTest.java
  src/test/java/underdogs/devbie/notice/controller/NoticeControllerTest.java
  src/test/java/underdogs/devbie/notice/domain/CompanyTest.java
  src/test/java/underdogs/devbie/notice/domain/DurationTest.java
  src/test/java/underdogs/devbie/notice/domain/NoticeDescriptionTest.java
  src/test/java/underdogs/devbie/notice/domain/NoticeTest.java
  src/test/java/underdogs/devbie/notice/service/NoticeServiceTest.java
Labels: 💡 Features, 📮 Server, 🔍 Review Required

#72 feat: 면접 답변 API 작성
  src/main/java/underdogs/devbie/answer/controller/AnswerController.java
  src/main/java/underdogs/devbie/answer/domain/Answer.java
  src/main/java/underdogs/devbie/answer/domain/Answers.java
  src/main/java/underdogs/devbie/answer/domain/repository/AnswerRepository.java
  src/main/java/underdogs/devbie/answer/dto/AnswerCreateRequest.java
  src/main/java/underdogs/devbie/answer/dto/AnswerResponse.java
  src/main/java/underdogs/devbie/answer/dto/AnswerResponses.java
  src/main/java/underdogs/devbie/answer/dto/AnswerUpdateRequest.java
  src/main/java/underdogs/devbie/answer/exception/AnswerNotExistedException.java
  src/main/java/underdogs/devbie/answer/exception/NotMatchedAnswerAuthorException.java
  src/main/java/underdogs/devbie/answer/service/AnswerService.java
  src/main/java/underdogs/devbie/auth/exception/UserNotFoundException.java
  src/test/java/underdogs/devbie/acceptance/AcceptanceTest.java
  src/test/java/underdogs/devbie/answer/acceptance/AnswerAcceptanceTest.java
  src/test/java/underdogs/devbie/answer/controller/AnswerControllerTest.java
  src/test/java/underdogs/devbie/answer/domain/AnswerTest.java
  src/test/java/underdogs/devbie/answer/domain/AnswersTest.java
  src/test/java/underdogs/devbie/answer/service/AnswerServiceTest.java
  src/test/java/underdogs/devbie/question/acceptance/QuestionAcceptanceTest.java
Labels: 💡 Features, 📮 Server, 🔍 Review Required

#73 feat: 추천 API 구현
  src/main/java/underdogs/devbie/answer/controller/AnswerController.java
  src/main/java/underdogs/devbie/auth/controller/interceptor/utils/InterceptorValidator.java
  src/main/java/underdogs/devbie/exception/AlreadyExistException.java
  src/main/java/underdogs/devbie/exception/NotExistException.java
  src/main/java/underdogs/devbie/notice/domain/Language.java
  src/main/java/underdogs/devbie/recommendation/controller/AnswerRecommendationController.java
  src/main/java/underdogs/devbie/recommendation/controller/QuestionRecommendationController.java
  src/main/java/underdogs/devbie/recommendation/domain/AnswerRecommendation.java
  src/main/java/underdogs/devbie/recommendation/domain/AnswerRecommendationRepository.java
  src/main/java/underdogs/devbie/recommendation/domain/QuestionRecommendation.java
  src/main/java/underdogs/devbie/recommendation/domain/QuestionRecommendationRepository.java
  src/main/java/underdogs/devbie/recommendation/domain/Recommendation.java
  src/main/java/underdogs/devbie/recommendation/dto/RecommendationRequest.java
  src/main/java/underdogs/devbie/recommendation/dto/RecommendationResponse.java
  src/main/java/underdogs/devbie/recommendation/service/AnswerRecommendationService.java
  src/main/java/underdogs/devbie/recommendation/service/QuestionRecommendationService.java
  src/test/java/underdogs/devbie/answer/domain/AnswersTest.java
  src/test/java/underdogs/devbie/notice/domain/NoticeTest.java
  src/test/java/underdogs/devbie/question/service/QuestionServiceTest.java
  src/test/java/underdogs/devbie/recommendation/RecommendationAcceptanceTest.java
  src/test/java/underdogs/devbie/recommendation/controller/AnswerRecommendationControllerTest.java
  src/test/java/underdogs/devbie/recommendation/controller/QuestionRecommendationControllerTest.java
  src/test/java/underdogs/devbie/recommendation/service/AnswerRecommendationServiceTest.java
  src/test/java/underdogs/devbie/recommendation/service/QuestionRecommendationServiceTest.java
Labels: 💡 Features, 📮 Server, 🔍 Review Required

#80 feat: 면접 질문 view 작성
  src/frontend/public/index.html
  src/frontend/src/App.vue
  src/frontend/src/api/index.js
  src/frontend/src/components/QuestionDetail.vue
  src/frontend/src/components/QuestionFilters.vue
  src/frontend/src/components/QuestionList.vue
  src/frontend/src/main.js
  src/frontend/src/router/index.js
  src/frontend/src/store/actions.js
  src/frontend/src/store/index.js
  src/frontend/src/store/mutations.js
  src/frontend/src/views/QuestionDetailView.vue
  src/frontend/src/views/QuestionListView.vue
  src/main/java/underdogs/devbie/question/service/QuestionService.java
  src/main/java/underdogs/devbie/recommendation/controller/QuestionRecommendationController.java
  src/main/java/underdogs/devbie/user/service/UserService.java
  src/test/java/underdogs/devbie/question/acceptance/QuestionAcceptanceTest.java
Labels: 🌈 View, 💡 Features

#86 refactor: 추천 api 수정
  src/main/java/underdogs/devbie/recommendation/controller/AnswerRecommendationController.java
  src/main/java/underdogs/devbie/recommendation/controller/QuestionRecommendationController.java
  src/main/java/underdogs/devbie/recommendation/controller/RecommendationController.java
  src/main/java/underdogs/devbie/recommendation/domain/AnswerRecommendation.java
  src/main/java/underdogs/devbie/recommendation/domain/AnswerRecommendationRepository.java
  src/main/java/underdogs/devbie/recommendation/domain/QuestionRecommendation.java
  src/main/java/underdogs/devbie/recommendation/domain/QuestionRecommendationRepository.java
  src/main/java/underdogs/devbie/recommendation/domain/Recommendation.java
  src/main/java/underdogs/devbie/recommendation/domain/RecommendationRepository.java
  src/main/java/underdogs/devbie/recommendation/domain/Recommendations.java
  src/main/java/underdogs/devbie/recommendation/dto/RecommendationCountResponse.java
  src/main/java/underdogs/devbie/recommendation/dto/RecommendationRequest.java
  src/main/java/underdogs/devbie/recommendation/dto/RecommendationResponse.java
  src/main/java/underdogs/devbie/recommendation/service/AnswerRecommendationService.java
  src/main/java/underdogs/devbie/recommendation/service/QuestionRecommendationService.java
  src/main/java/underdogs/devbie/recommendation/service/RecommendationService.java
  src/test/java/underdogs/devbie/recommendation/RecommendationAcceptanceTest.java
  src/test/java/underdogs/devbie/recommendation/controller/AnswerRecommendationControllerTest.java
  src/test/java/underdogs/devbie/recommendation/controller/QuestionRecommendationControllerTest.java
  src/test/java/underdogs/devbie/recommendation/service/AnswerRecommendationServiceTest.java
  src/test/java/underdogs/devbie/recommendation/service/QuestionRecommendationServiceTest.java
Labels: 📮 Server, 🛠 Refactoring

#93 feat: 화면에서 질문 생성, 수정, 삭제 기능 구현
  src/frontend/src/App.vue
  src/frontend/src/api/index.js
  src/frontend/src/components/CreateForm.vue
  src/frontend/src/components/EditForm.vue
  src/frontend/src/components/NavagationBar.vue
  src/frontend/src/components/QuestionDetail.vue
  src/frontend/src/router/index.js
  src/frontend/src/store/actions.js
  src/frontend/src/store/index.js
  src/frontend/src/store/mutations.js
  src/frontend/src/views/QuestionCreateView.vue
  src/frontend/src/views/QuestionDetailView.vue
  src/frontend/src/views/QuestionEditView.vue
  src/frontend/src/views/QuestionListView.vue
  src/main/java/underdogs/devbie/user/dto/UserResponse.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/resources/application.properties
Labels: 🌈 View, 💡 Features, 🔍 Review Required

#95 feature: v-app으로 변경하고, nav-bar 버튼 css 조정
  src/frontend/src/App.vue
  src/frontend/src/components/NavagationBar.vue
Labels: 🌈 View, 🛠 Refactoring

#100 feat: Logging 설정
  build.gradle
  src/main/java/underdogs/devbie/DevbieApplication.java
  src/main/java/underdogs/devbie/answer/domain/Answer.java
  src/main/java/underdogs/devbie/answer/domain/AnswerContent.java
  src/main/java/underdogs/devbie/answer/domain/Answers.java
  src/main/java/underdogs/devbie/aop/ControllerLoggingAspect.java
  src/main/java/underdogs/devbie/aop/ServiceLoggingAspect.java
  src/main/java/underdogs/devbie/auth/dto/AccessTokenRequest.java
  src/main/java/underdogs/devbie/auth/dto/AccessTokenResponse.java
  src/main/java/underdogs/devbie/auth/dto/JwtTokenResponse.java
  src/main/java/underdogs/devbie/auth/dto/UserInfoResponse.java
  src/main/java/underdogs/devbie/auth/dto/UserTokenDto.java
  src/main/java/underdogs/devbie/config/AopConfiguration.java
  src/main/java/underdogs/devbie/filter/ReadableRequestWrapperFilter.java
  src/main/java/underdogs/devbie/notice/domain/Company.java
  src/main/java/underdogs/devbie/notice/domain/Duration.java
  src/main/java/underdogs/devbie/notice/domain/Language.java
  src/main/java/underdogs/devbie/notice/domain/Notice.java
  src/main/java/underdogs/devbie/notice/domain/NoticeDescription.java
  src/main/java/underdogs/devbie/notice/dto/NoticeCreateRequest.java
  src/main/java/underdogs/devbie/notice/dto/NoticeDescriptionResponse.java
  src/main/java/underdogs/devbie/notice/dto/NoticeDetailResponse.java
  src/main/java/underdogs/devbie/notice/dto/NoticeResponse.java
  src/main/java/underdogs/devbie/notice/dto/NoticeResponses.java
  src/main/java/underdogs/devbie/notice/dto/NoticeUpdateRequest.java
  src/main/java/underdogs/devbie/question/domain/Question.java
  src/main/java/underdogs/devbie/question/domain/QuestionContent.java
  src/main/java/underdogs/devbie/question/domain/QuestionTitle.java
  src/main/java/underdogs/devbie/question/domain/Visits.java
  src/main/java/underdogs/devbie/question/dto/QuestionCreateRequest.java
  src/main/java/underdogs/devbie/question/dto/QuestionResponse.java
  src/main/java/underdogs/devbie/question/dto/QuestionResponses.java
  src/main/java/underdogs/devbie/question/dto/QuestionUpdateRequest.java
  src/main/java/underdogs/devbie/recommendation/domain/AnswerRecommendation.java
  src/main/java/underdogs/devbie/recommendation/domain/QuestionRecommendation.java
  src/main/java/underdogs/devbie/recommendation/dto/RecommendationRequest.java
  src/main/java/underdogs/devbie/recommendation/dto/RecommendationResponse.java
  src/main/java/underdogs/devbie/user/domain/User.java
  src/main/java/underdogs/devbie/user/dto/UserCreateRequest.java
  src/main/java/underdogs/devbie/user/dto/UserResponse.java
  src/main/resources/application.yml
  src/main/resources/log4j2.yml
Labels: 💡 Features, 📮 Server, 🔍 Review Required

#98 feat: Notice 리스트 페이지 작성 및 서버 연동
  package-lock.json
  src/frontend/src/App.vue
  src/frontend/src/api/index.js
  src/frontend/src/components/FooterBar.vue
  src/frontend/src/components/NavagationBar.vue
  src/frontend/src/components/NoticeFilters.vue
  src/frontend/src/components/NoticeList.vue
  src/frontend/src/components/NoticeType.vue
  src/frontend/src/router/index.js
  src/frontend/src/store/actions.js
  src/frontend/src/store/index.js
  src/frontend/src/store/mutations.js
  src/frontend/src/views/LoginPage.vue
  src/frontend/src/views/MainPage.vue
  src/frontend/src/views/NoticeListView.vue
  src/frontend/src/views/QuestionListView.vue
  src/main/resources/data.sql
Labels: 🌈 View, 💡 Features

#90 refactor: Notice 엔티티에 title,noticeType 필드 추가
  src/main/java/underdogs/devbie/notice/domain/Notice.java
  src/main/java/underdogs/devbie/notice/domain/NoticeType.java
  src/main/java/underdogs/devbie/notice/dto/NoticeCreateRequest.java
  src/main/java/underdogs/devbie/notice/dto/NoticeDetailResponse.java
  src/main/java/underdogs/devbie/notice/dto/NoticeResponse.java
  src/main/java/underdogs/devbie/notice/dto/NoticeResponses.java
  src/main/java/underdogs/devbie/notice/dto/NoticeUpdateRequest.java
  src/main/java/underdogs/devbie/recommendation/dto/RecommendationResponse.java
  src/test/java/underdogs/devbie/notice/acceptance/NoticeAcceptanceTest.java
  src/test/java/underdogs/devbie/notice/controller/NoticeControllerTest.java
  src/test/java/underdogs/devbie/notice/domain/NoticeTest.java
  src/test/java/underdogs/devbie/notice/service/NoticeServiceTest.java
Labels: 📮 Server, 🔍 Review Required, 🛠 Refactoring

#102 feat: AnswerList vue RD 작성
  src/frontend/src/api/index.js
  src/frontend/src/components/AnswerItem.vue
  src/frontend/src/components/AnswerList.vue
  src/frontend/src/store/actions.js
  src/frontend/src/store/index.js
  src/frontend/src/store/mutations.js
  src/frontend/src/views/QuestionDetailView.vue
  src/main/java/underdogs/devbie/answer/domain/AnswerContent.java
  src/main/java/underdogs/devbie/config/DummyDataConfiguration.java
  src/test/java/underdogs/devbie/answer/acceptance/AnswerAcceptanceTest.java
Labels: 🌈 View, 💡 Features

#104 fix: merge with develop
  src/frontend/src/App.vue
  src/frontend/src/api/index.js
  src/frontend/src/components/QuestionList.vue
  src/frontend/src/store/actions.js
  src/frontend/src/store/index.js
  src/frontend/src/views/MainPage.vue
  src/frontend/src/views/QuestionDetailView.vue
  src/frontend/src/views/QuestionListView.vue
  src/main/resources/data.sql
Labels: 🌈 View, 🐛 Bug, 📮 Server, 🛠 Refactoring

#108 refactor: nohup gitignore 추가
  .gitignore
Labels: ⚙️ Infra, 🛠 Refactoring

#106 test: 데모 테스트
  src/frontend/src/views/MainPage.vue
Labels: ⚙️ Infra
