Repository woowacourse-teams/2020-devbie, pull requests merged in 2020-08, with the labels that each got.

#114 refactor: 프론트 공동 코드 분리
  src/frontend/src/api/index.js
  src/frontend/src/components/notice/NoticeFilters.vue
  src/frontend/src/components/notice/NoticeList.vue
  src/frontend/src/components/notice/NoticeType.vue
  src/frontend/src/components/question/AnswerItem.vue
  src/frontend/src/components/question/AnswerList.vue
  src/frontend/src/components/question/CreateForm.vue
  src/frontend/src/components/question/EditForm.vue
  src/frontend/src/components/question/QuestionDetail.vue
  src/frontend/src/components/question/QuestionFilters.vue
  src/frontend/src/components/question/QuestionList.vue
  src/frontend/src/router/index.js
  src/frontend/src/store/actions.js
  src/frontend/src/store/index.js
  src/frontend/src/store/modules/answers.js
  src/frontend/src/store/modules/loginUser.js
  src/frontend/src/store/modules/notices.js
  src/frontend/src/store/modules/questions.js
  src/frontend/src/store/modules/recommendations.js
  src/frontend/src/store/mutations.js
  src/frontend/src/views/notice/NoticeListView.vue
  src/frontend/src/views/question/QuestionCreateView.vue
  src/frontend/src/views/question/QuestionDetailView.vue
  src/frontend/src/views/question/QuestionEditView.vue
  src/frontend/src/views/question/QuestionListView.vue
Labels: 🌈 View, 🛠 Refactoring

#82 refactor: 인수 테스트에 DynamicTest 적용
  src/frontend/public/index.html
  src/frontend/src/App.vue
  src/frontend/src/components/NavagationBar.vue
  src/frontend/src/components/notice/NoticeFilters.vue
  src/frontend/src/components/notice/NoticeList.vue
  src/frontend/src/components/notice/NoticeType.vue
  src/frontend/src/components/question/AnswerItem.vue
  src/frontend/src/components/question/AnswerList.vue
  src/frontend/src/components/question/CreateForm.vue
  src/frontend/src/components/question/EditForm.vue
  src/frontend/src/components/question/QuestionDetail.vue
  src/frontend/src/components/question/QuestionFilters.vue
  src/frontend/src/components/question/QuestionList.vue
  src/frontend/src/views/question/QuestionCreateView.vue
  src/frontend/src/views/question/QuestionDetailView.vue
  src/frontend/src/views/question/QuestionEditView.vue
  src/frontend/src/views/question/QuestionListView.vue
  src/main/java/underdogs/devbie/config/DummyDataConfiguration.java
  src/main/java/underdogs/devbie/recommendation/domain/AnswerRecommendationRepository.java
  src/main/java/underdogs/devbie/recommendation/domain/QuestionRecommendationRepository.java
  src/main/java/underdogs/devbie/recommendation/domain/RecommendationRepository.java
  src/main/java/underdogs/devbie/user/controller/UserController.java
  src/main/java/underdogs/devbie/user/service/UserService.java
  src/test/java/underdogs/devbie/acceptance/AcceptanceTest.java
  src/test/java/underdogs/devbie/answer/acceptance/AnswerAcceptanceTest.java
  src/test/java/underdogs/devbie/notice/acceptance/NoticeAcceptanceTest.java
  src/test/java/underdogs/devbie/question/acceptance/QuestionAcceptanceTest.java
  src/test/java/underdogs/devbie/recommendation/RecommendationAcceptanceTest.java
  src/test/java/underdogs/devbie/recommendation/acceptance/RecommendationAcceptanceTest.java
  src/test/java/underdogs/devbie/recommendation/controller/AnswerRecommendationControllerTest.java
  src/test/java/underdogs/devbie/recommendation/controller/QuestionRecommendationControllerTest.java
Labels: 🐛 Bug, 📮 Server, 🔍 Review Required, 🛠 Refactoring

#89 feat: 공고 게시글 생성,수정,삭제 권한 로직 추가
  src/main/java/underdogs/devbie/auth/controller/AuthController.java
  src/main/java/underdogs/devbie/auth/controller/interceptor/BearerAuthInterceptor.java
  src/main/java/underdogs/devbie/auth/controller/interceptor/annotation/Role.java
  src/main/java/underdogs/devbie/auth/controller/interceptor/utils/InterceptorValidator.java
  src/main/java/underdogs/devbie/auth/controller/resolver/LoginUserArgumentResolver.java
  src/main/java/underdogs/devbie/auth/dto/UserTokenDto.java
  src/main/java/underdogs/devbie/auth/exception/InvalidAuthorizationException.java
  src/main/java/underdogs/devbie/auth/jwt/JwtTokenProvider.java
  src/main/java/underdogs/devbie/config/AuthConfig.java
  src/main/java/underdogs/devbie/notice/controller/NoticeController.java
  src/main/java/underdogs/devbie/user/domain/RoleType.java
  src/main/java/underdogs/devbie/user/domain/User.java
  src/test/java/underdogs/devbie/acceptance/AcceptanceTest.java
  src/test/java/underdogs/devbie/auth/controller/AuthControllerTest.java
  src/test/java/underdogs/devbie/auth/jwt/JwtTokenProviderTest.java
  src/test/java/underdogs/devbie/notice/controller/NoticeControllerTest.java
Labels: 💡 Features, 📮 Server, 🔍 Review Required

#113 bugfix: POST요청시, 컨트롤러의 파라미터 로깅이 누락되는 문제 해결
  src/main/java/underdogs/devbie/aop/ControllerLoggingAspect.java
  src/main/java/underdogs/devbie/aop/ServiceLoggingAspect.java
  src/main/java/underdogs/devbie/filter/ReadableRequestWrapperFilter.java
Labels: 🐛 Bug, 🔍 Review Required, 🛠 Refactoring

#111 feat: 질문과 답변에 추천/비추천 액션 기능 추가
  src/frontend/src/App.vue
  src/frontend/src/api/index.js
  src/frontend/src/components/question/AnswerItem.vue
  src/frontend/src/components/question/AnswerList.vue
  src/frontend/src/components/question/QuestionDetail.vue
  src/frontend/src/components/question/QuestionList.vue
  src/frontend/src/store/modules/answers.js
  src/frontend/src/store/modules/recommendations.js
  src/frontend/src/views/question/QuestionDetailView.vue
  src/frontend/src/views/question/QuestionListView.vue
Labels: 🌈 View, 💡 Features, 🔍 Review Required

#120 fix: RoleType null 문제 해결
  src/main/java/underdogs/devbie/auth/dto/UserInfoResponse.java
  src/main/java/underdogs/devbie/user/domain/User.java
  src/main/java/underdogs/devbie/user/dto/UserResponse.java
Labels: 🐛 Bug, 📮 Server, 🛠 Refactoring

#122 feature: 공고 상세 페이지 구현 및 서버 연동
  src/frontend/src/App.vue
  src/frontend/src/components/notice/NoticeDetail.vue
  src/frontend/src/components/notice/NoticeList.vue
  src/frontend/src/components/notice/NoticeScroll.vue
  src/frontend/src/router/index.js
  src/frontend/src/store/modules/notices.js
  src/frontend/src/views/notice/NoticeDetailView.vue
Labels: 🌈 View, 💡 Features, 🔍 Review Required

#130 fix: 잘못된 route 경로 수정
  src/frontend/src/components/NavagationBar.vue
Labels: 🌈 View, 🐛 Bug

#133 refactor: mock 데이터 삽입을 data.sql로 통합
  src/main/java/underdogs/devbie/config/DummyDataConfiguration.java
  src/main/resources/data.sql
Labels: 📮 Server, 🔍 Review Required, 🛠 Refactoring

#137 fix: router-link가 붙은 버튼을 두 번이상 클릭시 에러 생기는 문제 해결
  src/frontend/src/router/index.js
Labels: 🌈 View, 🐛 Bug

#142 fix: 불필요한 fetch 삭제 및 fetch 파라미터 추가
  src/frontend/src/components/notice/NoticeDetail.vue
  src/frontend/src/components/notice/NoticeScroll.vue
Labels: 🌈 View, 🐛 Bug

#138 feat: 질문 생성 및 수정시 해시태그 등록기능
  src/frontend/src/components/question/AnswerItem.vue
  src/frontend/src/components/question/CreateForm.vue
  src/frontend/src/components/question/EditForm.vue
  src/frontend/src/components/question/FormButton.vue
  src/frontend/src/components/question/HashtagBox.vue
  src/frontend/src/components/question/QuestionCreate.vue
  src/frontend/src/components/question/QuestionDetail.vue
  src/frontend/src/components/question/QuestionEdit.vue
  src/frontend/src/store/modules/questions.js
  src/frontend/src/views/question/QuestionCreateView.vue
  src/frontend/src/views/question/QuestionEditView.vue
  src/frontend/vue.config.js
  src/main/java/underdogs/devbie/question/controller/HashtagController.java
  src/main/java/underdogs/devbie/question/domain/Hashtag.java
  src/main/java/underdogs/devbie/question/domain/HashtagRepository.java
  src/main/java/underdogs/devbie/question/domain/Question.java
  src/main/java/underdogs/devbie/question/domain/QuestionHashtag.java
  src/main/java/underdogs/devbie/question/domain/QuestionHashtagRepository.java
  src/main/java/underdogs/devbie/question/domain/QuestionHashtags.java
  src/main/java/underdogs/devbie/question/domain/QuestionRepository.java
  src/main/java/underdogs/devbie/question/domain/TagName.java
  src/main/java/underdogs/devbie/question/dto/HashtagCreateRequest.java
  src/main/java/underdogs/devbie/question/dto/HashtagResponse.java
  src/main/java/underdogs/devbie/question/dto/HashtagResponses.java
  src/main/java/underdogs/devbie/question/dto/HashtagUpdateRequest.java
  src/main/java/underdogs/devbie/question/dto/HashtagsRequest.java
  src/main/java/underdogs/devbie/question/dto/QuestionCreateRequest.java
  src/main/java/underdogs/devbie/question/dto/QuestionResponse.java
  src/main/java/underdogs/devbie/question/dto/QuestionUpdateRequest.java
  src/main/java/underdogs/devbie/question/exception/HashtagNotExistedException.java
  src/main/java/underdogs/devbie/question/service/HashtagService.java
  src/main/java/underdogs/devbie/question/service/QuestionHashtagService.java
  src/main/java/underdogs/devbie/question/service/QuestionService.java
  src/main/resources/data.sql
  src/test/java/underdogs/devbie/question/acceptance/HashtagAcceptanceTest.java
  src/test/java/underdogs/devbie/question/acceptance/QuestionAcceptanceTest.java
  src/test/java/underdogs/devbie/question/controller/HashtagControllerTest.java
  src/test/java/underdogs/devbie/question/controller/QuestionControllerTest.java
  src/test/java/underdogs/devbie/question/domain/HashtagTest.java
  src/test/java/underdogs/devbie/question/domain/QuestionHashtagTest.java
  src/test/java/underdogs/devbie/question/domain/QuestionHashtagsTest.java
  src/test/java/underdogs/devbie/question/domain/QuestionTest.java
  src/test/java/underdogs/devbie/question/domain/TagNameTest.java
  src/test/java/underdogs/devbie/question/service/HashtagServiceTest.java
  src/test/java/underdogs/devbie/question/service/QuestionHashtagServiceTest.java
  src/test/java/underdogs/devbie/question/service/QuestionServiceTest.java
Labels: 🌈 View, 💡 Features, 📮 Server, 🔍 Review Required, 🧪 Test

#147 feat: REST API 문서화 작업 - swagger
  build.gradle
  src/main/java/underdogs/devbie/answer/controller/AnswerController.java
  src/main/java/underdogs/devbie/config/SwaggerConfig.java
  src/main/java/underdogs/devbie/notice/controller/NoticeController.java
  src/main/java/underdogs/devbie/question/controller/QuestionController.java
  src/main/java/underdogs/devbie/recommendation/controller/RecommendationController.java
  src/main/java/underdogs/devbie/recommendation/service/QuestionRecommendationService.java
  src/main/java/underdogs/devbie/user/controller/UserController.java
Labels: 🌈 View, 💡 Features, 🔍 Review Required

#146 feat: 마이페이지 내 회원 정보 수정 기능 구현
  build.gradle
  src/frontend/src/api/index.js
  src/frontend/src/components/NavagationBar.vue
  src/frontend/src/components/user/MyPage.vue
  src/frontend/src/router/index.js
  src/frontend/src/store/modules/loginUser.js
  src/frontend/src/utils/validator.js
  src/frontend/src/views/user/MyPageView.vue
  src/main/java/underdogs/devbie/auth/dto/UserInfoDto.java
  src/main/java/underdogs/devbie/auth/oauth/GithubClient.java
  src/main/java/underdogs/devbie/auth/service/AuthService.java
  src/main/java/underdogs/devbie/aws/S3Service.java
  src/main/java/underdogs/devbie/user/controller/UserController.java
  src/main/java/underdogs/devbie/user/domain/User.java
  src/main/java/underdogs/devbie/user/dto/UserResponse.java
  src/main/java/underdogs/devbie/user/dto/UserUpdateImageRequest.java
  src/main/java/underdogs/devbie/user/dto/UserUpdateInfoRequest.java
  src/main/java/underdogs/devbie/user/exception/NotMatchedUserException.java
  src/main/java/underdogs/devbie/user/service/UserService.java
  src/test/java/underdogs/devbie/user/controller/UserControllerTest.java
  src/test/java/underdogs/devbie/user/domain/UserTest.java
  src/test/java/underdogs/devbie/user/service/UserServiceTest.java
Labels: 🌈 View, 💡 Features, 📮 Server, 🔍 Review Required

#150 feat : css 리팩토링 step1
  src/frontend/public/index.html
  src/frontend/src/App.vue
  src/frontend/src/components/FooterBar.vue
  src/frontend/src/components/NavagationBar.vue
  src/frontend/src/components/notice/NoticeDetail.vue
  src/frontend/src/components/question/QuestionFilters.vue
  src/frontend/src/components/question/QuestionList.vue
  src/frontend/src/views/notice/NoticeListView.vue
  src/frontend/src/views/question/QuestionDetailView.vue
  src/frontend/src/views/question/QuestionListView.vue
Labels: 🌈 View, 💡 Features, 🛠 Refactoring

#139 feat: 관리자 페이지 및 Notice CUD연동
  .gitignore
  package-lock.json
  src/frontend/src/components/NavagationBar.vue
  src/frontend/src/components/notice/NoticeDetail.vue
  src/frontend/src/components/notice/NoticeFilters.vue
  src/frontend/src/components/notice/NoticeList.vue
  src/frontend/src/components/notice/NoticeScroll.vue
  src/frontend/src/router/index.js
  src/frontend/src/store/modules/notices.js
  src/frontend/src/utils/noticeUtil.js
  src/frontend/src/views/admin/AdminMainView.vue
  src/frontend/src/views/notice/NoticeCreateView.vue
  src/frontend/src/views/notice/NoticeEditView.vue
  src/main/java/underdogs/devbie/answer/controller/AnswerController.java
  src/main/java/underdogs/devbie/notice/domain/NoticeDescription.java
  src/main/java/underdogs/devbie/notice/dto/NoticeCreateRequest.java
  src/main/java/underdogs/devbie/notice/dto/NoticeUpdateRequest.java
  src/test/java/underdogs/devbie/notice/acceptance/NoticeAcceptanceTest.java
  src/test/java/underdogs/devbie/notice/controller/NoticeControllerTest.java
  src/test/java/underdogs/devbie/notice/domain/NoticeDescriptionTest.java
  src/test/java/underdogs/devbie/notice/domain/NoticeTest.java
  src/test/java/underdogs/devbie/notice/service/NoticeServiceTest.java
Labels: 🌈 View, 🐶 Admin, 💡 Features

#154 hotfix: getters로 받아온 해시태그 데이터를 string 만 추출해야한다.
  src/frontend/src/components/question/QuestionEdit.vue
Labels: 🐛 Bug, 🛠 Refactoring

#158 feat: 공고 이미지 업로드 기능추가
  src/frontend/src/api/index.js
  src/frontend/src/components/notice/NoticeDetail.vue
  src/frontend/src/store/modules/notices.js
  src/frontend/src/views/notice/NoticeCreateView.vue
  src/frontend/src/views/notice/NoticeEditView.vue
  src/main/java/underdogs/devbie/notice/controller/NoticeController.java
  src/main/java/underdogs/devbie/notice/dto/ImageUploadRequest.java
  src/main/java/underdogs/devbie/notice/dto/NoticeCreateRequest.java
  src/test/java/underdogs/devbie/notice/controller/NoticeControllerTest.java
Labels: 🌈 View, 🐶 Admin, 💡 Features, 📮 Server

#160 fix: 본문 줄바꿈 되도록 변경
  src/frontend/public/index.html
  src/frontend/src/components/question/AnswerItem.vue
  src/frontend/src/components/question/QuestionDetail.vue
Labels: 🌈 View, 🐛 Bug, 🛠 Refactoring

#156 feat: InterceptorValidator Bean 등록
  src/main/java/underdogs/devbie/auth/controller/interceptor/BearerAuthInterceptor.java
  src/main/java/underdogs/devbie/auth/controller/interceptor/utils/InterceptorValidator.java
Labels: 🔍 Review Required, 🛠 Refactoring

#148 feat : 질문 목록 해시태그로 필터링 및 조회수, 추천수, 생성시간 순으로 정렬
  gradlew
  src/frontend/src/App.vue
  src/frontend/src/components/NavagationBar.vue
  src/frontend/src/components/hashtag/HashtagList.vue
  src/frontend/src/components/question/AnswerItem.vue
  src/frontend/src/components/question/AnswerList.vue
  src/frontend/src/components/question/QuestionControl.vue
  src/frontend/src/components/question/QuestionDetail.vue
  src/frontend/src/components/question/QuestionFilters.vue
  src/frontend/src/components/question/QuestionList.vue
  src/frontend/src/router/index.js
  src/frontend/src/store/index.js
  src/frontend/src/store/modules/answers.js
  src/frontend/src/store/modules/hashtags.js
  src/frontend/src/store/modules/loginUser.js
  src/frontend/src/store/modules/questions.js
  src/frontend/src/store/modules/recommendations.js
  src/frontend/src/views/hashtags/HashtagsView.vue
  src/frontend/src/views/question/QuestionListView.vue
  src/main/java/underdogs/devbie/answer/domain/Answer.java
  src/main/java/underdogs/devbie/answer/domain/RecommendationCount.java
  src/main/java/underdogs/devbie/answer/dto/AnswerResponse.java
  src/main/java/underdogs/devbie/question/controller/HashtagController.java
  src/main/java/underdogs/devbie/question/controller/QuestionController.java
  src/main/java/underdogs/devbie/question/domain/OrderBy.java
  src/main/java/underdogs/devbie/question/domain/Question.java
  src/main/java/underdogs/devbie/question/domain/QuestionHashtagRepository.java
  src/main/java/underdogs/devbie/question/domain/QuestionRepository.java
  src/main/java/underdogs/devbie/question/domain/RecommendationCount.java
  src/main/java/underdogs/devbie/question/dto/HashtagsRequest.java
  src/main/java/underdogs/devbie/question/dto/QuestionResponse.java
  src/main/java/underdogs/devbie/question/service/QuestionHashtagService.java
  src/main/java/underdogs/devbie/question/service/QuestionService.java
  src/main/java/underdogs/devbie/recommendation/controller/RecommendationController.java
  src/main/java/underdogs/devbie/recommendation/domain/Recommendations.java
  src/main/java/underdogs/devbie/recommendation/dto/RecommendationCountResponse.java
  src/main/java/underdogs/devbie/recommendation/service/AnswerRecommendationService.java
  src/main/java/underdogs/devbie/recommendation/service/QuestionRecommendationService.java
  src/main/java/underdogs/devbie/recommendation/service/RecommendationService.java
  src/main/resources/data.sql
  src/test/java/underdogs/devbie/acceptance/AcceptanceTest.java
  src/test/java/underdogs/devbie/answer/domain/AnswerTest.java
  src/test/java/underdogs/devbie/question/acceptance/QuestionAcceptanceTest.java
  src/test/java/underdogs/devbie/question/controller/QuestionControllerTest.java
  src/test/java/underdogs/devbie/question/service/QuestionHashtagServiceTest.java
  src/test/java/underdogs/devbie/question/service/QuestionServiceTest.java
  src/test/java/underdogs/devbie/recommendation/acceptance/RecommendationAcceptanceTest.java
  src/test/java/underdogs/devbie/recommendation/controller/AnswerRecommendationControllerTest.java
  src/test/java/underdogs/devbie/recommendation/controller/QuestionRecommendationControllerTest.java
  src/test/java/underdogs/devbie/recommendation/service/AnswerRecommendationServiceTest.java
  src/test/java/underdogs/devbie/recommendation/service/QuestionRecommendationServiceTest.java
Labels: 🌈 View, 💡 Features, 📮 Server, 🔍 Review Required, 🛠 Refactoring

#178 feat: 채팅 view 작성
  src/frontend/src/App.vue
  src/frontend/src/components/chat/ChatDrawer.vue
  src/frontend/src/components/chat/ChatInput.vue
  src/frontend/src/components/chat/ChatItem.vue
  src/frontend/src/components/chat/ChatList.vue
  src/frontend/src/components/notice/NoticeDetail.vue
  src/frontend/src/store/index.js
  src/frontend/src/store/modules/chat.js
Labels: 🌈 View, 💡 Features

#172 refactor: 면접 질문 도메인 리팩토링
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/public/index.html
  src/frontend/src/App.vue
  src/frontend/src/components/NavagationBar.vue
  src/frontend/src/components/hashtag/HashtagList.vue
  src/frontend/src/components/question/AnswerCreate.vue
  src/frontend/src/components/question/AnswerItem.vue
  src/frontend/src/components/question/AnswerList.vue
  src/frontend/src/components/question/FormButton.vue
  src/frontend/src/components/question/FormTitle.vue
  src/frontend/src/components/question/HashtagBox.vue
  src/frontend/src/components/question/MarkdownContent.vue
  src/frontend/src/components/question/QuestionControl.vue
  src/frontend/src/components/question/QuestionCreate.vue
  src/frontend/src/components/question/QuestionDetail.vue
  src/frontend/src/components/question/QuestionDetailMenu.vue
  src/frontend/src/components/question/QuestionEdit.vue
  src/frontend/src/components/question/QuestionFilters.vue
  src/frontend/src/components/question/QuestionForm.vue
  src/frontend/src/components/question/QuestionList.vue
  src/frontend/src/components/question/RecommendationControl.vue
  src/frontend/src/main.js
  src/frontend/src/router/index.js
  src/frontend/src/store/modules/questions.js
  src/frontend/src/store/modules/recommendations.js
  src/frontend/src/utils/editor.js
  src/frontend/src/views/admin/AdminMainView.vue
  src/frontend/src/views/question/QuestionCreateView.vue
  src/frontend/src/views/question/QuestionDetailView.vue
  src/frontend/src/views/question/QuestionEditView.vue
  src/main/java/underdogs/devbie/answer/domain/repository/AnswerRepository.java
  src/main/java/underdogs/devbie/answer/dto/AnswerResponse.java
  src/main/java/underdogs/devbie/answer/dto/AnswerResponses.java
  src/main/java/underdogs/devbie/answer/service/AnswerService.java
  src/main/java/underdogs/devbie/question/domain/QuestionContent.java
  src/main/java/underdogs/devbie/question/dto/HashtagResponse.java
  src/main/java/underdogs/devbie/question/dto/QuestionResponse.java
  src/main/java/underdogs/devbie/question/service/QuestionService.java
  src/main/java/underdogs/devbie/user/dto/UserCreateRequest.java
  src/main/resources/data.sql
  src/test/java/underdogs/devbie/acceptance/AcceptanceTest.java
  src/test/java/underdogs/devbie/answer/controller/AnswerControllerTest.java
  src/test/java/underdogs/devbie/answer/domain/AnswersTest.java
  src/test/java/underdogs/devbie/answer/service/AnswerServiceTest.java
  src/test/java/underdogs/devbie/question/acceptance/QuestionAcceptanceTest.java
  src/test/java/underdogs/devbie/question/controller/QuestionControllerTest.java
  src/test/java/underdogs/devbie/question/service/QuestionServiceTest.java
  src/test/java/underdogs/devbie/user/controller/UserControllerTest.java
  src/test/java/underdogs/devbie/user/domain/UserTest.java
Labels: 🌈 View, 💡 Features, 🔍 Review Required, 🛠 Refactoring

#186 feat: 채팅 서버 구현
  build.gradle
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/components/chat/ChatDrawer.vue
  src/frontend/src/components/chat/ChatInput.vue
  src/frontend/src/components/notice/NoticeDetail.vue
  src/frontend/src/store/modules/chat.js
  src/frontend/vue.config.js
  src/main/java/underdogs/devbie/aop/ControllerLoggingAspect.java
  src/main/java/underdogs/devbie/chat/controller/ChatController.java
  src/main/java/underdogs/devbie/chat/domain/Chat.java
  src/main/java/underdogs/devbie/chat/domain/ChatRepository.java
  src/main/java/underdogs/devbie/chat/domain/ChatRoom.java
  src/main/java/underdogs/devbie/chat/domain/ChatRoomRepository.java
  src/main/java/underdogs/devbie/chat/dto/ChatRoomResponse.java
  src/main/java/underdogs/devbie/chat/dto/MessageResponse.java
  src/main/java/underdogs/devbie/chat/dto/MessageResponses.java
  src/main/java/underdogs/devbie/chat/dto/MessageSendRequest.java
  src/main/java/underdogs/devbie/chat/service/ChatService.java
  src/main/java/underdogs/devbie/config/ChatConfig.java
  src/test/java/underdogs/devbie/chat/controller/ChatControllerTest.java
  src/test/java/underdogs/devbie/chat/service/ChatServiceTest.java
Labels: 💡 Features, 📮 Server

#189 hotfix: vue 라이브러리 버전 업데이트
  src/frontend/package-lock.json
Labels: 🐛 Bug

#183 feat: 공고 인피니티 스크롤 및 검색 기능 추가
  src/frontend/src/components/notice/NoticeCreate.vue
  src/frontend/src/components/notice/NoticeDetail.vue
  src/frontend/src/components/notice/NoticeEdit.vue
  src/frontend/src/components/notice/NoticeFilters.vue
  src/frontend/src/components/notice/NoticeList.vue
  src/frontend/src/components/notice/NoticeScroll.vue
  src/frontend/src/components/notice/NoticeSearch.vue
  src/frontend/src/components/notice/NoticeType.vue
  src/frontend/src/store/modules/notices.js
  src/frontend/src/views/notice/NoticeListView.vue
  src/main/java/underdogs/devbie/notice/controller/NoticeController.java
  src/main/java/underdogs/devbie/notice/domain/NoticeRepositoryCustom.java
  src/main/java/underdogs/devbie/notice/domain/NoticeRepositoryImpl.java
  src/main/java/underdogs/devbie/notice/dto/CustomPageRequest.java
  src/main/java/underdogs/devbie/notice/dto/NoticeReadRequest.java
  src/main/java/underdogs/devbie/notice/dto/NoticeResponses.java
  src/main/java/underdogs/devbie/notice/service/NoticeService.java
  src/main/java/underdogs/devbie/notice/service/cache/NoticeKeyGenerator.java
  src/main/java/underdogs/devbie/notice/vo/JobPositionsResponse.java
  src/main/java/underdogs/devbie/notice/vo/LanguagesResponse.java
  src/main/java/underdogs/devbie/notice/vo/NoticeCacheVo.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/underdogs/devbie/notice/acceptance/NoticeAcceptanceTest.java
  src/test/java/underdogs/devbie/notice/controller/NoticeControllerTest.java
  src/test/java/underdogs/devbie/notice/service/NoticeServiceTest.java
Labels: 🌈 View, 💡 Features, 📮 Server

#190 feat: 채팅 view 기본 기능 보완
  src/frontend/src/App.vue
  src/frontend/src/components/chat/ChatDrawer.vue
  src/frontend/src/components/chat/ChatInput.vue
  src/frontend/src/components/chat/ChatItem.vue
  src/frontend/src/components/chat/ChatList.vue
  src/frontend/src/components/chat/chatInfo.vue
  src/frontend/src/components/notice/NoticeDetail.vue
  src/frontend/src/store/modules/chat.js
  src/main/java/underdogs/devbie/chat/dto/MessageResponse.java
Labels: 🌈 View, 💡 Features

#196 feat: 인원수 동기화
  src/frontend/src/store/modules/chat.js
  src/main/java/underdogs/devbie/chat/controller/ChatController.java
  src/main/java/underdogs/devbie/chat/domain/ChatNames.java
  src/main/java/underdogs/devbie/chat/domain/ChatRoom.java
  src/main/java/underdogs/devbie/chat/domain/StompMethodType.java
  src/main/java/underdogs/devbie/chat/dto/ChatNameResponse.java
  src/main/java/underdogs/devbie/chat/dto/MessageResponse.java
  src/main/java/underdogs/devbie/chat/dto/StompMessageResponse.java
  src/main/java/underdogs/devbie/chat/dto/StompMessageResponseData.java
  src/main/java/underdogs/devbie/chat/service/ChatService.java
  src/test/java/underdogs/devbie/chat/controller/ChatControllerTest.java
  src/test/java/underdogs/devbie/chat/service/ChatServiceTest.java
Labels: 💡 Features, 📮 Server, 🔍 Review Required, 🛠 Refactoring

#199 Refactor/채팅 이름 형용사 동물 이름 추가 및 메서드 명 변경
  src/main/java/underdogs/devbie/chat/domain/Adjective.java
  src/main/java/underdogs/devbie/chat/domain/Animal.java
  src/main/java/underdogs/devbie/chat/domain/ChatName.java
  src/main/java/underdogs/devbie/chat/domain/ChatNameFactory.java
  src/main/java/underdogs/devbie/chat/domain/ChatNames.java
  src/main/java/underdogs/devbie/chat/domain/ChatRoom.java
  src/main/java/underdogs/devbie/chat/domain/Noun.java
  src/main/java/underdogs/devbie/chat/service/ChatService.java
  src/test/java/underdogs/devbie/chat/controller/ChatControllerTest.java
  src/test/java/underdogs/devbie/chat/domain/ChatNameFactoryTest.java
  src/test/java/underdogs/devbie/chat/domain/ChatNameTest.java
  src/test/java/underdogs/devbie/chat/domain/ChatNamesTest.java
  src/test/java/underdogs/devbie/chat/domain/ChatRoomTest.java
  src/test/java/underdogs/devbie/chat/domain/ChatTest.java
  src/test/java/underdogs/devbie/chat/service/ChatServiceTest.java
Labels: 📮 Server, 🔍 Review Required, 🛠 Refactoring

#195 feat: 공고 및 질문 즐겨찾기 기능 구현
  src/frontend/src/components/NavagationBar.vue
  src/frontend/src/components/favorite/FavoriteControl.vue
  src/frontend/src/components/favorite/FavoriteType.vue
  src/frontend/src/components/favorite/NoticeFavorites.vue
  src/frontend/src/components/favorite/QuestionFavorites.vue
  src/frontend/src/components/notice/NoticeList.vue
  src/frontend/src/components/question/QuestionDetail.vue
  src/frontend/src/router/index.js
  src/frontend/src/store/index.js
  src/frontend/src/store/modules/favorite.js
  src/frontend/src/views/favorite/NoticeFavoriteView.vue
  src/frontend/src/views/favorite/QuestionFavoriteView.vue
  src/main/java/underdogs/devbie/favorite/controller/FavoriteController.java
  src/main/java/underdogs/devbie/favorite/controller/NoticeFavoriteController.java
  src/main/java/underdogs/devbie/favorite/controller/QuestionFavoriteController.java
  src/main/java/underdogs/devbie/favorite/domain/Favorite.java
  src/main/java/underdogs/devbie/favorite/domain/FavoriteRepository.java
  src/main/java/underdogs/devbie/favorite/domain/NoticeFavorite.java
  src/main/java/underdogs/devbie/favorite/domain/NoticeFavoriteRepository.java
  src/main/java/underdogs/devbie/favorite/domain/QuestionFavorite.java
  src/main/java/underdogs/devbie/favorite/domain/QuestionFavoriteRepository.java
  src/main/java/underdogs/devbie/favorite/service/FavoriteService.java
  src/main/java/underdogs/devbie/favorite/service/NoticeFavoriteService.java
  src/main/java/underdogs/devbie/favorite/service/QuestionFavoriteService.java
  src/main/java/underdogs/devbie/notice/service/NoticeService.java
  src/main/java/underdogs/devbie/question/service/QuestionService.java
  src/test/java/underdogs/devbie/acceptance/AcceptanceTest.java
  src/test/java/underdogs/devbie/favorite/acceptance/NoticeFavoriteAcceptanceTest.java
  src/test/java/underdogs/devbie/favorite/acceptance/QuestionFavoriteAcceptanceTest.java
  src/test/java/underdogs/devbie/favorite/controller/NoticeFavoriteControllerTest.java
  src/test/java/underdogs/devbie/favorite/controller/QuestionFavoriteControllerTest.java
  src/test/java/underdogs/devbie/favorite/domain/NoticeFavoriteTest.java
  src/test/java/underdogs/devbie/favorite/domain/QuestionFavoriteTest.java
  src/test/java/underdogs/devbie/favorite/service/NoticeFavoriteServiceTest.java
  src/test/java/underdogs/devbie/favorite/service/QuestionFavoriteServiceTest.java
  src/test/java/underdogs/devbie/notice/acceptance/NoticeAcceptanceTest.java
  src/test/java/underdogs/devbie/notice/service/NoticeServiceTest.java
  src/test/java/underdogs/devbie/question/service/QuestionServiceTest.java
Labels: 🌈 View, 💡 Features, 📮 Server, 🔍 Review Required

#193 refactor: 공고 디자인 수정
  src/frontend/src/App.vue
  src/frontend/src/components/notice/NoticeDetail.vue
  src/frontend/src/components/notice/NoticeFilters.vue
  src/frontend/src/components/notice/NoticeList.vue
  src/frontend/src/components/notice/NoticeScroll.vue
  src/frontend/src/components/notice/NoticeSearch.vue
  src/frontend/src/components/notice/NoticeType.vue
  src/frontend/src/router/index.js
  src/frontend/src/views/notice/NoticeDetailView.vue
Labels: 🌈 View, 🛠 Refactoring

#203 feat: 메인페이지 변경
  src/frontend/src/components/NavagationBar.vue
  src/frontend/src/router/index.js
Labels: 🌈 View

#200 fix: NickName Color 중복 허용 및 ChatName 랜덤 추출
  src/main/java/underdogs/devbie/chat/domain/ChatNameFactory.java
  src/main/java/underdogs/devbie/chat/domain/TitleColorFactory.java
  src/test/java/underdogs/devbie/chat/domain/ChatNameFactoryTest.java
Labels: 🐛 Bug, 💡 Features, 🛠 Refactoring

#211 refactor: 스넥바 통일 및 STOMP 로그 제거
  src/frontend/src/store/modules/chat.js
Labels: 📮 Server, 🔍 Review Required, 🛠 Refactoring

#213 hotfix: 의도치 않은 disconnect 로그 제거
  src/frontend/src/store/modules/chat.js
Labels: 🌈 View, 🐛 Bug

#207 feat: 구글 애널리틱스 적용
  .travis.yml
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/main.js
Labels: 🌈 View, 💡 Features

#205 fix: 불필요한 텍스트 제거 및 컴포넌트 길이 고정
  src/frontend/src/components/notice/NoticeDetail.vue
  src/frontend/src/components/notice/NoticeScroll.vue
Labels: 🌈 View, 💡 Features

#209 bugfix: 즐겨찾기 상태 동기화
  src/frontend/src/App.vue
  src/frontend/src/components/favorite/NoticeFavorites.vue
  src/frontend/src/components/notice/NoticeList.vue
  src/frontend/src/components/question/QuestionDetail.vue
  src/frontend/src/components/question/QuestionList.vue
  src/frontend/src/store/modules/favorite.js
Labels: 🌈 View, 🐛 Bug

#208 feature : 면접질문 무한 스크롤, 검색기능
  src/frontend/src/components/NavagationBar.vue
  src/frontend/src/components/hashtag/HashtagBox.vue
  src/frontend/src/components/hashtag/HashtagList.vue
  src/frontend/src/components/question/CreateForm.vue
  src/frontend/src/components/question/HashtagBox.vue
  src/frontend/src/components/question/QuestionFilters.vue
  src/frontend/src/components/question/QuestionForm.vue
  src/frontend/src/components/question/QuestionList.vue
  src/frontend/src/components/question/RecommendationControl.vue
  src/frontend/src/components/question/SearchBar.vue
  src/frontend/src/router/index.js
  src/frontend/src/store/modules/hashtags.js
  src/frontend/src/store/modules/questions.js
  src/frontend/src/utils/validator.js
  src/frontend/src/views/question/QuestionListView.vue
  src/main/java/underdogs/devbie/question/controller/QuestionController.java
  src/main/java/underdogs/devbie/question/domain/OrderBy.java
  src/main/java/underdogs/devbie/question/domain/QuestionRepository.java
  src/main/java/underdogs/devbie/question/domain/QuestionRepositoryCustom.java
  src/main/java/underdogs/devbie/question/domain/QuestionRepositoryImpl.java
  src/main/java/underdogs/devbie/question/dto/QuestionPageRequest.java
  src/main/java/underdogs/devbie/question/dto/QuestionReadRequest.java
  src/main/java/underdogs/devbie/question/dto/QuestionResponses.java
  src/main/java/underdogs/devbie/question/service/QuestionService.java
  src/main/resources/data.sql
  src/test/java/underdogs/devbie/acceptance/AcceptanceTest.java
  src/test/java/underdogs/devbie/question/acceptance/QuestionAcceptanceTest.java
  src/test/java/underdogs/devbie/question/controller/QuestionControllerTest.java
  src/test/java/underdogs/devbie/question/service/QuestionServiceTest.java
Labels: 🌈 View, 💡 Features, 📮 Server, 🧪 Test

#215 fix: npm build가 안되던 문제 해결
  src/frontend/package-lock.json
Labels: 🐛 Bug

#218 refactor: 기본이미지 지정, 날짜 포맷 지정, 개행수정
  src/frontend/package-lock.json
  src/frontend/src/components/notice/NoticeCreate.vue
  src/frontend/src/components/notice/NoticeDetail.vue
Labels: 🐛 Bug, 🛠 Refactoring, 🧪 Test

#221 fix: 채팅방 이슈 해결
  src/frontend/src/App.vue
  src/frontend/src/components/chat/ChatList.vue
Labels: 🌈 View, 🐛 Bug

#219 feat: AWS S3 설정 추가
  src/main/resources/application.yml
Labels: ⚙️ Infra, 🐛 Bug

#223 fix: subquery 형식 변경
  src/frontend/src/components/question/QuestionList.vue
  src/main/java/underdogs/devbie/question/domain/QuestionContent.java
  src/main/java/underdogs/devbie/question/domain/RecommendationCount.java
Labels: 📮 Server

#225 fix: 공고리스트 화면에서 로그아웃 기능 수정
  src/frontend/src/components/notice/NoticeList.vue
Labels: 🌈 View, 🐛 Bug

#227 fix: hashtag & answer subquery bug
  src/frontend/src/components/question/QuestionForm.vue
  src/frontend/src/components/question/QuestionList.vue
  src/frontend/src/store/modules/questions.js
  src/frontend/src/views/question/QuestionListView.vue
  src/main/java/underdogs/devbie/answer/domain/RecommendationCount.java
Labels: 🌈 View, 🐛 Bug

#231 fix: 답변 수정시 마크다운 적용 안되는 문제
  src/frontend/src/components/question/AnswerItem.vue
Labels: 🌈 View
